/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Juan Martinez Sanjurjo (https://sketchfab.com/JuanSanjurjo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/advanced-game-characters-week-2-jacket-8f211f057bb24f5db17ca659553b716b
title: Advanced Game Characters - Week 2 Jacket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  console.log("props in Model ", props)
  const group = useRef()
  const { nodes, materials } = useGLTF(`/${props.productId}.glb`)

  if (props.productId == "629df7ee762a181375e54f04"){
    return (
      <group ref={group} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
          <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: '2d6fb9c83fae49a6a04a7d7e495a47f0.fbx' }}>
            <group userData={{ name: 'RootNode' }}>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'watch body bottom_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.watch_body_bottom_low_watch_body_bottom_0.geometry} material={materials.watch_body_bottom} userData={{ name: 'watch body bottom_low_watch body bottom_0' }} />
              </group>
              <group position={[-0.83, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'watch head_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.watch_head_low_watch_head_0.geometry} material={materials.watch_head} userData={{ name: 'watch head_low_watch head_0' }} />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'watch body top_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.watch_body_top_low_watch_body_top_0.geometry} material={materials.watch_body_top} userData={{ name: 'watch body top_low_watch body top_0' }} />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'watch inside_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.watch_inside_low_watch_inside_0.geometry} material={materials.watch_inside} userData={{ name: 'watch inside_low_watch inside_0' }} />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'watch pointers' }}>
                <mesh castShadow receiveShadow geometry={nodes.watch_pointers_pointers_0.geometry} material={materials.pointers} userData={{ name: 'watch pointers_pointers_0' }} />
              </group>
              <group position={[-1.16, 0.25, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'belt small part_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.belt_small_part_low_belt_small_lether_0.geometry} material={materials.belt_small_lether} userData={{ name: 'belt small part_low_belt small lether_0' }} />
              </group>
              <group position={[-0.85, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'belt fixer_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.belt_fixer_low_belt_fixer_0.geometry} material={materials.belt_fixer} userData={{ name: 'belt fixer_low_belt fixer_0' }} />
              </group>
              <group position={[-0.01, -0.58, -36.05]} rotation={[-Math.PI / 2, 0, 0]} scale={19.8} userData={{ name: 'belt02_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.belt02_low_belt_02_0.geometry} material={materials.belt_02} userData={{ name: 'belt02_low_belt 02_0' }} />
              </group>
              <group position={[0.55, -2.42, 54.55]} rotation={[-Math.PI / 2, 0, 0]} scale={19.88} userData={{ name: 'belt01_low' }}>
                <mesh castShadow receiveShadow geometry={nodes.belt01_low_belt_01_0.geometry} material={materials.belt_01} userData={{ name: 'belt01_low_belt 01_0' }} />
              </group>
              <group position={[-2.43, -5.88, 36.14]} rotation={[-Math.PI / 2, 0, 0]} scale={38.23} userData={{ name: 'watch glass_high.001' }}>
                <mesh castShadow receiveShadow geometry={nodes.watch_glass_high001_watch_glass_0.geometry} material={materials.watch_glass} userData={{ name: 'watch glass_high.001_watch glass_0' }} />
              </group>
              <group position={[-2.43, -5.88, 36.14]} rotation={[-Math.PI / 2, 0, 0]} scale={38.23} userData={{ name: 'stitches' }}>
                <mesh castShadow receiveShadow geometry={nodes.stitches_stitches_0.geometry} material={materials.stitches} userData={{ name: 'stitches_stitches_0' }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    )
  }

  else if (props.productId == "6288fca2cf6785cbfd5d8d23"){
  return (
    <group ref={group} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh material-color={props.color} geometry={nodes.defaultMaterial.geometry} material={materials.Jacket_Lv2_Jacket} />
        </group> 
      </group>
    </group>
  )
  }
  else if (props.productId=="629484e5e3acff4e1c71a7e4") {
    return(
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
        <group userData={{ name: 'root' }}>
         <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'GLTF_SceneRootNode' }}>
            <group position={[0.39, 0.3, 0.32]} scale={[0.05, 0.02, 0.05]} userData={{ name: 'Cube.015_1' }}>
              <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Material.006']} userData={{ name: 'Object_4' }} />
              <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['Material.031']} userData={{ name: 'Object_5' }} />
            </group>
            <group position={[0.48, 0.24, 0.12]} scale={[0.82, 1, 1]} userData={{ name: 'Cube_2' }}>
              <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['Material.025']} userData={{ name: 'Object_7' }} />
              <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Material.002']} userData={{ name: 'Object_8' }} />
              <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['Material.007']} userData={{ name: 'Object_9' }} />
              <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.005']} userData={{ name: 'Object_10' }} />
            </group>
            <group position={[0.48, 0.29, -0.28]} rotation={[0.02, 0, 0]} scale={[0.82, 1, 1]} userData={{ name: 'Plane_3' }}>
              <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials['Material.006']} userData={{ name: 'Object_12' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials['Material.007']} userData={{ name: 'Object_13' }} />
             </group>
             <group position={[0.48, 0.32, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.61, 1]} userData={{ name: 'Cube.001_4' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials['Material.025']} userData={{ name: 'Object_15' }} />
              <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials['Material.003']} userData={{ name: 'Object_16' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials['Material.004']} userData={{ name: 'Object_17' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials['Material.008']} userData={{ name: 'Object_18' }} />
            </group>
            <group position={[0.47, 0.19, 0.66]} userData={{ name: 'Plane.001_5' }}>
              <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials['Material.025']} userData={{ name: 'Object_20' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials['Material.002']} userData={{ name: 'Object_21' }} />
             </group>
             <group position={[1.37, 0.18, 0.66]} scale={[1, 1.72, 1]} userData={{ name: 'Cube.002_6' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials['Material.007']} userData={{ name: 'Object_23' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials['Material.006']} userData={{ name: 'Object_24' }} />
             </group>
             <group position={[1.4, 0.3, 0.72]} rotation={[0.17, 0, 0]} scale={[1.2, 0.95, 0.95]} userData={{ name: 'Cube.003_7' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials['Material.005']} userData={{ name: 'Object_26' }} />
             </group>
             <group position={[1.4, 0.26, 0.14]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.004_8' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials['Material.010']} userData={{ name: 'Object_28' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials['Material.011']} userData={{ name: 'Object_29' }} />
             </group>
            <group position={[1.4, 0.26, 0.07]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.005_9' }}>
              <mesh castShadow receiveShadow geometry={nodes.Object_31.geometry} material={materials['Material.010']} userData={{ name: 'Object_31' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials['Material.011']} userData={{ name: 'Object_32' }} />
             </group>
             <group position={[1.4, 0.26, 0.14]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.006_10' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials['Material.010']} userData={{ name: 'Object_34' }} />
              <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials['Material.011']} userData={{ name: 'Object_35' }} />
             </group>
             <group position={[0.48, 0.24, 0.16]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.82, 1, 1]} userData={{ name: 'Cube.007_11' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials['Material.005']} userData={{ name: 'Object_37' }} />
             </group>
             <group position={[-0.43, 0.26, 0.13]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.008_12' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials['Material.010']} userData={{ name: 'Object_39' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials['Material.011']} userData={{ name: 'Object_40' }} />
             </group>
            <group position={[0.48, 0.24, 0.24]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.82, 1, 1]} userData={{ name: 'Cube.009_13' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials['Material.005']} userData={{ name: 'Object_42' }} />
             </group>
            <group position={[-0.43, 0.26, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.010_14' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials['Material.010']} userData={{ name: 'Object_44' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_45.geometry} material={materials['Material.011']} userData={{ name: 'Object_45' }} />
             </group>
             <group position={[0.48, 0.22, 0.67]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0, 0.04]} userData={{ name: 'Cube.011_15' }}>
              <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials['Material.010']} userData={{ name: 'Object_47' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_48.geometry} material={materials['Material.011']} userData={{ name: 'Object_48' }} />
             </group>
            <group position={[0.46, 1.04, 0.74]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.1, 0.1]} userData={{ name: 'Circle_16' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_50.geometry} material={materials['Material.025']} userData={{ name: 'Object_50' }} />
             </group>
             <group position={[-0.46, 0.26, 0.05]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0, 0.02]} userData={{ name: 'Cube.012_17' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_52.geometry} material={materials['Material.010']} userData={{ name: 'Object_52' }} />
               <mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials['Material.011']} userData={{ name: 'Object_53' }} />
             </group>
             <group position={[-0.5, 0.26, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={0} userData={{ name: 'Plane.002_18' }}>
               <mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials.material_0} userData={{ name: 'Object_55' }} />
             </group>
           </group>
         </group>
       </group>
     </group>
 )

  }
}

// export default function Laptop_model({ ...props }) {
//   const group = useRef()
//   const { nodes, materials } = useGLTF('/scene.gltf')
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
//         <group userData={{ name: 'root' }}>
//           <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'GLTF_SceneRootNode' }}>
//             <group position={[0.39, 0.3, 0.32]} scale={[0.05, 0.02, 0.05]} userData={{ name: 'Cube.015_1' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Material.006']} userData={{ name: 'Object_4' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['Material.031']} userData={{ name: 'Object_5' }} />
//             </group>
//             <group position={[0.48, 0.24, 0.12]} scale={[0.82, 1, 1]} userData={{ name: 'Cube_2' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['Material.025']} userData={{ name: 'Object_7' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Material.002']} userData={{ name: 'Object_8' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['Material.007']} userData={{ name: 'Object_9' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.005']} userData={{ name: 'Object_10' }} />
//             </group>
//             <group position={[0.48, 0.29, -0.28]} rotation={[0.02, 0, 0]} scale={[0.82, 1, 1]} userData={{ name: 'Plane_3' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials['Material.006']} userData={{ name: 'Object_12' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials['Material.007']} userData={{ name: 'Object_13' }} />
//             </group>
//             <group position={[0.48, 0.32, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.61, 1]} userData={{ name: 'Cube.001_4' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials['Material.025']} userData={{ name: 'Object_15' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials['Material.003']} userData={{ name: 'Object_16' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials['Material.004']} userData={{ name: 'Object_17' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials['Material.008']} userData={{ name: 'Object_18' }} />
//             </group>
//             <group position={[0.47, 0.19, 0.66]} userData={{ name: 'Plane.001_5' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials['Material.025']} userData={{ name: 'Object_20' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials['Material.002']} userData={{ name: 'Object_21' }} />
//             </group>
//             <group position={[1.37, 0.18, 0.66]} scale={[1, 1.72, 1]} userData={{ name: 'Cube.002_6' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials['Material.007']} userData={{ name: 'Object_23' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials['Material.006']} userData={{ name: 'Object_24' }} />
//             </group>
//             <group position={[1.4, 0.3, 0.72]} rotation={[0.17, 0, 0]} scale={[1.2, 0.95, 0.95]} userData={{ name: 'Cube.003_7' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials['Material.005']} userData={{ name: 'Object_26' }} />
//             </group>
//             <group position={[1.4, 0.26, 0.14]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.004_8' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials['Material.010']} userData={{ name: 'Object_28' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials['Material.011']} userData={{ name: 'Object_29' }} />
//             </group>
//             <group position={[1.4, 0.26, 0.07]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.005_9' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_31.geometry} material={materials['Material.010']} userData={{ name: 'Object_31' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials['Material.011']} userData={{ name: 'Object_32' }} />
//             </group>
//             <group position={[1.4, 0.26, 0.14]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.006_10' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials['Material.010']} userData={{ name: 'Object_34' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials['Material.011']} userData={{ name: 'Object_35' }} />
//             </group>
//             <group position={[0.48, 0.24, 0.16]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.82, 1, 1]} userData={{ name: 'Cube.007_11' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials['Material.005']} userData={{ name: 'Object_37' }} />
//             </group>
//             <group position={[-0.43, 0.26, 0.13]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.008_12' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials['Material.010']} userData={{ name: 'Object_39' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials['Material.011']} userData={{ name: 'Object_40' }} />
//             </group>
//             <group position={[0.48, 0.24, 0.24]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.82, 1, 1]} userData={{ name: 'Cube.009_13' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials['Material.005']} userData={{ name: 'Object_42' }} />
//             </group>
//             <group position={[-0.43, 0.26, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.02, 0, 0.03]} userData={{ name: 'Cube.010_14' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials['Material.010']} userData={{ name: 'Object_44' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_45.geometry} material={materials['Material.011']} userData={{ name: 'Object_45' }} />
//             </group>
//             <group position={[0.48, 0.22, 0.67]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0, 0.04]} userData={{ name: 'Cube.011_15' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials['Material.010']} userData={{ name: 'Object_47' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_48.geometry} material={materials['Material.011']} userData={{ name: 'Object_48' }} />
//             </group>
//             <group position={[0.46, 1.04, 0.74]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.1, 0.1]} userData={{ name: 'Circle_16' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_50.geometry} material={materials['Material.025']} userData={{ name: 'Object_50' }} />
//             </group>
//             <group position={[-0.46, 0.26, 0.05]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0, 0.02]} userData={{ name: 'Cube.012_17' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_52.geometry} material={materials['Material.010']} userData={{ name: 'Object_52' }} />
//               <mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials['Material.011']} userData={{ name: 'Object_53' }} />
//             </group>
//             <group position={[-0.5, 0.26, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={0} userData={{ name: 'Plane.002_18' }}>
//               <mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials.material_0} userData={{ name: 'Object_55' }} />
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }


useGLTF.preload('/jacket_model.glb')
useGLTF.preload('/laptop_model.glb')
useGLTF.preload('/watch_model.glb')